--- 
repository: https://github.com/destructuring/definition-precise
application: precise

user: nobody
group: nobody

ruby_loader: /usr/local/rvm/bin/rvm-exe
deploy_ruby: default
app_ruby: default

branches: [ master ]
branch_regex: /

chef_path: .

notify:
  nothing:
